# Generated by Django 4.0.5 on 2022-12-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DronCount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_review',
            new_name='logData',
        ),
    ]
