# Generated by Django 4.0.5 on 2022-12-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DronCount', '0003_rename_lang_gmap_latitude_rename_lati_gmap_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countdetails',
            old_name='name',
            new_name='annotation_name',
        ),
    ]
