# Generated by Django 4.0.5 on 2022-12-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DronCount', '0004_rename_name_countdetails_annotation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_Timestamp'),
        ),
    ]
