# Generated by Django 4.1.4 on 2022-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DronCount', '0007_rename_latitude_gmap_lat_rename_longitude_gmap_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='drone_location',
        ),
        migrations.AlterField(
            model_name='drone',
            name='Next_maintainance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time in service'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='purchase_year',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time in service'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='time_in_service',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time in service'),
        ),
    ]
