# Generated by Django 4.1.4 on 2022-12-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DronCount", "0009_drone_is_on_drone_last_update_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gmap",
            old_name="Lat",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="gmap",
            old_name="Lng",
            new_name="lng",
        ),
        migrations.RemoveField(
            model_name="drone",
            name="is_on",
        ),
        migrations.AddField(
            model_name="gmap",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
