# Generated by Django 4.1.4 on 2022-12-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DronCount", "0011_gmap_drone"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="purchase_day",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drone",
            name="purchase_month",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drone",
            name="Next_maintainance",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Time in service"
            ),
        ),
        migrations.AlterField(
            model_name="drone",
            name="purchase_year",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drone",
            name="time_in_service",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Time in service"
            ),
        ),
    ]
