# Generated by Django 4.1.4 on 2022-12-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DronCount", "0013_remove_drone_purchase_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="purchase_year",
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
