# Generated by Django 4.1.4 on 2022-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DronCount", "0014_alter_drone_purchase_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="purchase_year",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
