# Generated by Django 4.1.4 on 2022-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DronCount", "0015_alter_drone_purchase_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="purchase_year",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="last_update_timestamp"
            ),
        ),
    ]
