# Generated by Django 4.0.5 on 2022-12-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
